### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [freeshrugsxd/qgis-pathfinder#1]
# Problem

![metadata-pl](https://user-images.githubusercontent.com/2510900/95448474-afc0ea00-0963-11eb-8aa0-53f40bdd1c50.png)

**Comment by freeshrugsxd** [comment]
Hey! Thank you for quick response!

I assume you want me to add a homepage to metadata.txt?

**Comment by NyakudyaA** [comment]
> Hey! Thank you for quick response!
> 
> I assume you want me to add a homepage to metadata.txt?

Yes and then upload the plugin again

**Comment by freeshrugsxd** [comment]
Done
