### ISSUE TITLE
"The plugin pathfinder caused QGIS to crash"

### ISSUE THREAD

**Issue by AlisterH** [freeshrugsxd/qgis-pathfinder#6]
Feel free to close this as I don't have a stack trace or anything, but I wanted to file it just to let you know there might be an issue.

I was not interacting with the pathfinder plugin - I just right-clicked on the layer at the bottom of my layer tree and clicked "move to top", and QGIS claims that "Plugin pathfinder crashed QGIS".

I've had the same or similar crashes previously, which QGIS blamed on pathfinder even though I wasn't interacting with it. They weren't with 2.26.2, as I only installed that this morning, but I can't remember if I had any prior to 2.26.0
```
Python Stack Trace
Windows fatal exception: access violation

Current thread 0x000077ac (most recent call first):
  File "C:\Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pathfinder\lib\layertreecontextmenumanager.py", line 112 in eventFilter
    menu.exec(self.view.mapToGlobal(event.pos()))


Stack Trace
No stack trace is available.


QGIS Info
QGIS Version: 3.26.2-Buenos Aires
QGIS code revision: feec3d3b12f
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

```

**Comment by freeshrugsxd** [comment]
Hey @AlisterH,
thank you for your report but as you said, there isn't much to go on. I work with 3.26.2 myself and I haven't had any issue like that and cannot replicate it right now on my personal machine.

I have had issues with crashes concerning access violations tho. But I feel like they happen more often when I work on a layout and not the main window and pathfinder doesn't do anything in the layout window.

> I was not interacting with the pathfinder plugin


There is a short interaction happening whenever you right-click a layer in the Layers panel. That's probably why it is shown as the current thread.


You could try and deactivate pathfinder (or _try with a fresh profile™_?) and see if the problem persists. 

But I can't rule out anything so if you want you can send me a project where this happens and tell me what settings you use and I will keep trying to replicate the issue.

regards

**Comment by AlisterH** [comment]
> I have had issues with crashes concerning access violations tho. But I feel like they happen more often when I work on a layout and not the main window and pathfinder doesn't do anything in the layout window.

I don't normally use layouts so I wouldn't know if the layout window has recent problems.
 
> > I was not interacting with the pathfinder plugin
> 
> There is a short interaction happening whenever you right-click a layer in the Layers panel. That's probably why it is shown as the current thread.

OK, it just seemed strange that it didn't crash straight away on the right-click, but after I clicked "move to top".

> You could try and deactivate pathfinder (or _try with a fresh profile™_?) and see if the problem persists.

Yes, I deactivated it when I filed the ticket.  It isn't enough testing to conclude anything, but I haven't had any similar crashes since (only some crashes in another plugin that are easily reproduceable and clearly unrelated).
I have now reenabled it and installed the First Aid plugin to see if it helps with debugging these crashes.

**Comment by freeshrugsxd** [comment]
Hey @AlisterH,

just checking in if you ran into any more problems related to this issue?

**Comment by AlisterH** [comment]
I've probably only seen it a couple of times this year.
Haven't been set up for debugging at the time.

**Comment by freeshrugsxd** [comment]
Closing for now, feel free to ping me if any issue should arise again
